### ISSUE TITLE
Add tendrl-notifier package build into centos-ci

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [usmqe/usmqe-centos-ci#20]
Add tendrl-notifier build trigger into centos-ci for master and release branch

**Comment by dahorak** [comment]
Build trigger for master branch is created and working:
https://ci.centos.org/view/tendrl-build-master/job/tendrl-build-1-master-notifier/

Build trigger for release branch is created, but the build is failing:
https://ci.centos.org/view/tendrl-build-release/job/tendrl-build-1-release-notifier/
I'll debug it and fix it or create relevant issue in the tendrl-notifier repo.

**Comment by dahorak** [comment]
Build trigger for release branch is working as expected since release 1.5.2.
Closing this issue.
